name: MERN Stack CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongo --eval 'db.runCommand({ ping: 1 })'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Node.js for frontend
      - name: Set up Node.js (frontend)
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'

      # Install frontend dependencies
      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      # Build frontend
      - name: Build frontend
        run: |
          cd frontend
          npm run build

      # Setup Node.js for backend
      - name: Set up Node.js (backend)
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'

      # Install backend dependencies
      - name: Install backend dependencies
        run: |
          cd backend
          npm install

      # Start backend
      - name: Start backend
        run: |
          cd backend
          node app.js
